# Generated by Django 5.1.7 on 2025-03-12 20:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('medication_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Medication ID')),
                ('name', models.CharField(max_length=100, verbose_name='Medication Name')),
                ('dosage', models.TextField(verbose_name='Medication Dosage')),
                ('frequency', models.TextField(verbose_name='Medication Frequency')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='Medication Manufacturer')),
                ('side_effects', models.TextField(verbose_name='Medication Side Effects')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
            ],
        ),
    ]
