# Generated by Django 5.1.7 on 2025-03-12 20:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('billing_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Billing ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total amount')),
                ('payment_date', models.DateTimeField(verbose_name='Payment Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.appointment', verbose_name='Appointment')),
            ],
        ),
    ]
