# Generated by Django 5.1.7 on 2025-03-12 20:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Notification ID')),
                ('message', models.TextField(verbose_name='Message')),
                ('notification_type', models.CharField(choices=[('AP', 'Appointment Remainder'), ('PA', 'Payment ALERT'), ('SY', 'System Message'), ('OT', 'Other')], default='OT', max_length=2, verbose_name='Notification Type')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is Read')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
            ],
        ),
    ]
