# Generated by Django 5.1.7 on 2025-03-12 20:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('medication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('prescription_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Prescription ID')),
                ('instruction', models.TextField(verbose_name='Instructions')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.appointment', verbose_name='Appointment')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medication.medication', verbose_name='Medication')),
            ],
        ),
    ]
