# Generated by Django 5.1.7 on 2025-03-12 20:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Appointment ID')),
                ('appointment_date', models.DateTimeField(verbose_name='Appointment Date')),
                ('appointment_status', models.CharField(choices=[('PN', 'PENDING'), ('CP', 'COMPLETED'), ('CL', 'CANCELLED')], default='PN', max_length=2, verbose_name='Appointment Status')),
                ('reason_visiting', models.TextField(verbose_name='Reason For Visit')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
            ],
        ),
    ]
