# Generated by Django 5.1.7 on 2025-03-13 02:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Medical History ID')),
                ('diagnosis', models.TextField(verbose_name='Daignosis')),
                ('date_of_diagnosis', models.DateField(verbose_name='Diagnosis Date')),
                ('notes', models.TextField(verbose_name='Additional Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient', verbose_name='Patient')),
            ],
        ),
    ]
