# Generated by Django 5.1.7 on 2025-03-14 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_history', '0001_initial'),
        ('patients', '0003_remove_patient_medical_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalhistory',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_history', to='patients.patient', verbose_name='Patient'),
        ),
    ]
