# Generated by Django 5.1.7 on 2025-03-15 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_history', '0002_alter_medicalhistory_patient'),
        ('patients', '0003_remove_patient_medical_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalhistory',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_histories', to='patients.patient', verbose_name='Patient'),
        ),
    ]
