# Generated by Django 5.1.7 on 2025-03-12 20:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Patient ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Patient Age')),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], default='M', max_length=1, verbose_name='Patient Gender')),
                ('dob', models.DateTimeField(verbose_name='Patient Date of Birth')),
                ('address', models.TextField(verbose_name='Patient Address')),
                ('contact', models.TextField(verbose_name='Patient Contact')),
                ('email', models.EmailField(max_length=254, verbose_name='Patient Email')),
                ('emergency_contact', models.TextField(verbose_name='Emergency Contact')),
                ('insurance_number', models.CharField(max_length=50, verbose_name='Insurance Number')),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='O+', max_length=3, verbose_name='Blood Group')),
                ('medical_history', models.TextField(verbose_name='Medical History')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
            ],
        ),
    ]
