# Generated by Django 5.1.7 on 2025-03-14 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='medical_history',
        ),
    ]
