# Generated by Django 5.1.7 on 2025-03-12 20:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Doctor ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('specialization', models.CharField(max_length=100, verbose_name="Doctor's Specialization")),
                ('qualification', models.CharField(max_length=100, verbose_name="Doctor's Qualification")),
                ('contact', models.CharField(max_length=50, verbose_name="Doctor's Contact")),
                ('email', models.EmailField(max_length=254, verbose_name="Doctor's Email")),
                ('availability', models.JSONField(verbose_name='Availability')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
            ],
        ),
    ]
