# Generated by Django 5.1.7 on 2025-03-12 20:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Department ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Department Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Department Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
            ],
        ),
    ]
